on:
  workflow_dispatch:

name: CreateDeploymentStack

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: non-prod

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Bicep linter
        run: az bicep build --file ./main.bicep
      - name: Run Bicep Param linter
        run: az bicep build-params --file ./parameters.bicepparam

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/checkout@v3
      - uses: azure/arm-deploy@v1
        name: Run preflight validation
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ secrets.AZURE_RG }}
          template: ./main.bicep
          parameters: ./parameters.bicepparam
          deploymentMode: Validate
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, validate]
    steps:
      - uses: actions/checkout@v3
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - uses: actions/checkout@v3
      - name: Deploy Bicep template using deployment group
        run: |
            az stack group create \
              --name "deploymentStack" \
              --action-on-unmanage detachAll \
              --deny-settings-mode none \
              --resource-group "rg-jm-hubandspoke-dev-uks-01" \
              --template-file main.bicep \
              --parameters parameters.bicepparam 